#Arreglos y clases

##Matrices

In [ ]:
A = [[1,2,3],[4,5,6],[7,8,9]]
print (A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
B=[[21,34,40], [71,17,77], [73,81,28]]
A+B,

2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
A[0][0]
[1,2,3]
#A[0,0]

[1, 2, 3]

##Vectores y Listas

In [ ]:
L=A[0]
M=B[0]

In [ ]:
a=L[0]
b=M[0]
a+b

22

In [ ]:
a==1

True

In [ ]:
L+M

[1, 2, 3, 21, 34, 40]

###Suma de "Vectores"

In [ ]:
len(L)==len(M)


True

In [ ]:
suma=[L[0]+M[0],L[1]+M[1],L[2]+M[2]]
suma

[22, 36, 43]

In [ ]:
suma=[L[i]+M[i]for i in range(3)]
suma

[22, 36, 43]

##Creación de funciones globales
La función para crear funciones es `def`que se cierra con un debug (`print` o `return`)

In [ ]:
def Hola():
  print ("Hola yo soy mateo")

In [ ]:
Hola()

Hola yo soy mateo


In [ ]:
def Saludar (s,n):
  print (f"Hola, yo soy {s} no me importa yo {n}")

In [ ]:
Saludar("Mateo", "Guapo")

Hola, yo soy Mateo no me importa yo Guapo


In [ ]:
def par(x):
  for x in range(10):
    if x%2==0:
      print(f"{x} es par")
    else:
        print(f"{x} es impar")

In [ ]:
par(10)

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [ ]:
def suma_vectorial(L,M):
  x=[L[i]+M[i] for i in range(len(L))]
  return x

In [ ]:
L=[1,2,3]
M=[21,34,40]
suma_vectorial(L,M)

[22, 36, 43]

##Modulos o Librerias

In [ ]:
import math
from math import sqrt, pi

In [ ]:
sqrt(68)

8.246211251235321

In [ ]:
pi

3.141592653589793

##El modulo Numphy
la función array


In [ ]:
import numpy as np
L_vector = np.array(L)
M_vector = np.array(M)
L_vector + M_vector

array([22, 36, 43])

In [ ]:
C = [9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]
C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [ ]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])

In [ ]:
A_matriz @ C_matriz

array([[76, 36, 21],
       [17, 42, 12],
       [43, 67, 52]])